/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.informatica.poo.interfaces;

import br.edu.ifrn.informatica.poo.Agenda;
import br.edu.ifrn.informatica.poo.Contato;
import br.edu.ifrn.informatica.poo.excecoes.ContatoNaoEncontrado;
import java.awt.Component;
import java.awt.Container;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.SwingUtilities;

/**
 *
 *
 */
public class JIFBuscarContatos extends javax.swing.JInternalFrame {

    public static TmBuscarContatos modelo;
    public Agenda agenda;
	private static int linhaSelecionada = -1;
    /**
     * Creates new form JIFVerContato
     */
    public JIFBuscarContatos(Agenda agenda) {
        //agenda
	this.agenda = agenda;
        initComponents();
        setClosable(true);
        refreshPopulate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
		jbExcluir.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		if(linhaSelecionada != -1){
        			Contato contato = modelo.getContato(linhaSelecionada);
        			agenda.removerContato(contato);
        			refreshPopulate();
        			jTable1.repaint();
        		}        	
        	}
        });
		
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextCpf = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextEmail = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextNome = new javax.swing.JTextPane();
        jbBuscar = new javax.swing.JButton();

        setClosable(true);

		modelo = new TmBuscarContatos();
		
        jTable1.setModel(modelo);
		
		jTable1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		linhaSelecionada = jTable1.getSelectedRow();
        		
        		Point p = e.getPoint();
        		if (e.getClickCount() == 2) {
        			        			
        			Container container = SwingUtilities.getAncestorOfClass(JDesktopPane.class, (Component)e.getSource());
                    if (container != null){
                        JDesktopPane desktopPane = getDesktopPane();
						Contato contato = new Contato();
						contato = modelo.getContato(linhaSelecionada);
						
						
                        JIFDetalhesContato jdc = new JIFDetalhesContato(agenda, contato);
                        desktopPane.add(jdc);//add f1 to desktop pane
                        jdc.setResizable(true);
            			jdc.pack();
            			jdc.setVisible(true);
                        ;
                       /* Dimension desktopSize = getDesktopPane().getSize();
                        f1.setSize(desktopSize);
                        f1.setPreferredSize(desktopSize);
                        MainClass.dontmoveframe();*/
                    } 
        			JIFDetalhesContato jdc = new JIFDetalhesContato(agenda, modelo.getContato(linhaSelecionada));
        			
        		}
        	}
        });
		
		
		
        jScrollPane1.setViewportView(jTable1);
		if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }
        jTable1.setVisible(true);

        JbCancelar.setText("Cancelar");
        JbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
       

        jLabel1.setText("");

        jLabel2.setText("CPF:");

        jLabel3.setText("Email:");

        jLabel4.setText("Nome:");

        jScrollPane2.setViewportView(jTextCpf);

        jScrollPane3.setViewportView(jTextEmail);

        jScrollPane4.setViewportView(jTextNome);

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try{
					jbBuscarActionPerformed(evt);
				}
				catch(Exception e){
					
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbCancelar)
                    .addComponent(jbExcluir))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JbCancelarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) throws ContatoNaoEncontrado {                                         
        if(!jTextNome.getText().isEmpty()){
            modelo.setLinhas(agenda.buscarContatoPorNome(jTextNome.getText()));
        }
        else if(!jTextCpf.getText().isEmpty()){
            modelo.setLinhas(agenda.buscarContatoPorCPF(jTextCpf.getText()));
        }
        else if(!jTextEmail.getText().isEmpty()){
            modelo.setLinhas(agenda.buscarContatoPorEmail(jTextEmail.getText()));
        }
        else{
            
        }
        jTable1.repaint();
    }                                         

    public void refreshPopulate(){
    	modelo.getLinhas().clear();
    	modelo.setLinhas(agenda.getContatos());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextCpf;
    private javax.swing.JTextPane jTextEmail;
    private javax.swing.JTextPane jTextNome;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbExcluir;
    // End of variables declaration//GEN-END:variables
}
