/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.informatica.poo.interfaces;

import br.edu.ifrn.informatica.poo.Agenda;
import br.edu.ifrn.informatica.poo.Contato;
import java.awt.Component;
import java.awt.Container;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JDesktopPane;
import javax.swing.SwingUtilities;

/**
 *
 *
 */
public class JIFVerContatos extends javax.swing.JInternalFrame {

    public static TmVerContatos modelo;
    public Agenda agenda;
	private static int linhaSelecionada = -1;
    /**
     * Creates new form JIFVerContato
     */
    public JIFVerContatos(Agenda agenda) {
        //agenda
		this.agenda = agenda;
        initComponents();
        setClosable(true);
        refreshPopulate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
		jbExcluir.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		if(linhaSelecionada != -1){
        			Contato contato = modelo.getContato(linhaSelecionada);
        			agenda.removerContato(contato);
        			refreshPopulate();
        			jTable1.repaint();
        		}        	
        	}
        });
		
        setClosable(true);

		modelo = new TmVerContatos(agenda.getContatos());
		
        jTable1.setModel(modelo);
		
		jTable1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		linhaSelecionada = jTable1.getSelectedRow();
        		
        		Point p = e.getPoint();
        		if (e.getClickCount() == 2) {
        			        			
        			Container container = SwingUtilities.getAncestorOfClass(JDesktopPane.class, (Component)e.getSource());
                    if (container != null){
                        JDesktopPane desktopPane = getDesktopPane();
                        JIFDetalhesContato jdc = new JIFDetalhesContato(agenda, modelo.getContato(linhaSelecionada));
                        desktopPane.add(jdc);//add f1 to desktop pane
                        jdc.setResizable(true);
            			jdc.pack();
            			jdc.setVisible(true);
                        ;
                       /* Dimension desktopSize = getDesktopPane().getSize();
                        f1.setSize(desktopSize);
                        f1.setPreferredSize(desktopSize);
                        MainClass.dontmoveframe();*/
                    } 
        			JIFDetalhesContato jdc = new JIFDetalhesContato(agenda, modelo.getContato(linhaSelecionada));
        			
        		}
        	}
        });
		
		
		
        jScrollPane1.setViewportView(jTable1);
		if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        }
        jTable1.setVisible(true);
		
		
		
        JbCancelar.setText("Cancelar");
        JbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbCancelar)
                    .addComponent(jbExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JbCancelarActionPerformed


    public void refreshPopulate(){
    	modelo.getLinhas().clear();
    	modelo.setLinhas(agenda.getContatos());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbExcluir;
    // End of variables declaration//GEN-END:variables
}
